wanted_zones = [
    "02.1.01",
    "02.2.02",
    "02.2.03",
    "03.2.01",
    "03.2.02",
    "05.1.02",
    "05.1.04",
    "08.2.03",
    "09.1.01",
    "11.1.02",
    "12.2.02",
    "14.1.01",
    "18.1.01",
    "19.1.01",
    "21.1.01",
    "22.1.01",
    "24.1.01",
    "25.2.01",
    "25.2.02",
    "25.2.03",
    "26.2.02",
    "26.2.03",
    "26.2.04",
    "28.1.02",
    "30.1.06",
    "31.1.01"
]

[zone_names]
"02.1.01" = "Tijuana"
"02.2.02" = "Ensenada"
"02.2.03" = "Mexicali"
"03.2.01" = "La Paz"
"03.2.02" = "Los Cabos"
"05.1.02" = "Monclova-Frontera"
"05.1.04" = "Saltillo"
"08.2.03" = "Ciudad Juárez"
"09.1.01" = "Ciudad de México"
"11.1.02" = "León"
"12.2.02" = "Acapulco"
"14.1.01" = "Guadalajara"
"18.1.01" = "Tepic"
"19.1.01" = "Monterrey"
"21.1.01" = "Puebla - Tlaxcala"
"22.1.01" = "Querétaro"
"24.1.01" = "San Luis Potosí"
"25.2.01" = "Culiacán"
"25.2.02" = "Los Mochis"
"25.2.03" = "Mazatlán"
"26.2.02" = "Ciudad Obregón"
"26.2.03" = "Hermosillo"
"26.2.04" = "Nogales"
"28.1.02" = "Tampico"
"30.1.06" = "Veracruz"
"31.1.01" = "Mérida"
